version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/ECommerce
    networks:
      - app_network

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:5000
    networks:
      - app_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
